Audio/WAVFileReader.cpp
Audio/WaveBankReader.cpp
Inc/Audio.h
Src/AlphaTestEffect.cpp
Src/BasicEffect.cpp
Src/BasicPostProcess.cpp
Src/Bezier.h
Src/DDSTextureLoader.cpp
Src/DGSLEffect.cpp
Src/DemandCreate.h
Src/EffectCommon.cpp
Src/EnvironmentMapEffect.cpp
Src/GamePad.cpp
Src/GeometricPrimitive.cpp
Src/Geometry.cpp
Src/LoaderHelpers.h
Src/Model.cpp
Src/PlatformHelpers.h
Src/PrimitiveBatch.cpp
Src/ScreenGrab.cpp
Src/SpriteBatch.cpp
Src/SpriteFont.cpp
Src/WICTextureLoader.cpp
Src/XboxDDSTextureLoader.cpp
Src/dds.h
Src/pch.h
XWBTool/xwbtool.cpp

The change here is to make the _DirectX Tool Kit_ math code build correctly with DirectXMath 3.12 or later when using ``_XM_NO_XMVECTOR_OVERLOADS_``.

Fix compiler errors (Clang 6)

---

Src/ModelLoadSDKMESH.cpp

There is no direct DXGI equivalent to the legacy Direct3D 9 vertex format ``D3DDECLTYPE_DEC3N``. It's a signed 10:10:10 normalized format. Some legacy DirectX SDK samples for DX10 / DX 11 just treat it as ``DXGI_FORMAT_R10G10B10A2_UNORM`` which kind of works.
This update uses that hack for DirectXTK, but emits a warning a debug builds.

SDKMESH updated to load models using legacy DEC3N compressed normals

---

DirectXTK_Desktop_2015.vcxproj
DirectXTK_Desktop_2015.vcxproj.filters
DirectXTK_Desktop_2015_Win10.vcxproj
DirectXTK_Desktop_2015_Win10.vcxproj.filters
DirectXTK_Desktop_2017.vcxproj
DirectXTK_Desktop_2017.vcxproj.filters
DirectXTK_Desktop_2017_Win10.vcxproj
DirectXTK_Desktop_2017_Win10.vcxproj.filters
DirectXTK_Windows10.vcxproj
DirectXTK_Windows10.vcxproj.filters
DirectXTK_Windows10_2015.vcxproj
DirectXTK_Windows10_2015.vcxproj.filters
DirectXTK_XboxOneXDK_2015.vcxproj
DirectXTK_XboxOneXDK_2015.vcxproj.filters
DirectXTK_XboxOneXDK_2017.vcxproj
DirectXTK_XboxOneXDK_2017.vcxproj.filters
Inc/Effects.h
Src/DGSLEffectFactory.cpp
Src/EffectFactory.cpp
Src/ModelLoadCMO.cpp
Src/ModelLoadSDKMESH.cpp
Src/PBREffectFactory.cpp
Src/SDKMesh.h

Adds ``PBREffectFactory`` class and ``sdkmesh2`` materials loading
> EffectInfo now has one more texture for emissive channel, with DGSLEffectInfo updated to have one less array entry to maintain the 8 texture slots.

SDKMESH2 export support for PBR materials

---

Inc/SpriteFont.h
Src/SpriteFont.cpp

There is momentum to adopting [UTF-8 Everywhere](http://utf8everywhere.org/) which currently makes a it a little difficult to work with SpriteFont that uses ``wchar_t``. The library should be updated with DrawString, MeasureString, and MeasureDrawBounds overloads that take ``char`` assuming it's UTF-8 (not ASCII or some other codepage).

SpriteFont should support UTF-8 strings

---

Src/DDSTextureLoader.cpp
Src/WICTextureLoader.cpp

If you pass a 'non-null' value to the DDS or WIC texture loaders, but when calling the ``Ex`` version you provide a ``bindFlags`` without the ``D3D11_BIND_SHADER_RESOURCE`` then it will fail when it calls ``CreateShaderResourceView``.
This PR adds validation early in the function to catch this rather than failing later on...

Ex texture loaders updated with additional parameter validation

---

Inc/ScreenGrab.h
Src/ScreenGrab.cpp

With the new 'flip' style presentation model for Windows 10 or later, you don't actually use ``*_SRGB`` on the backbuffer format. Therefore, the resulting ``PNG`` screenshot would be washed out.
This adds a new optional paraemeter to allow forcing the sRGB metadata.

Added optioal forceSRGB parameter to SaveWICTextureToFile

---

Inc/Model.h
Src/ModelLoadCMO.cpp
Src/ModelLoadSDKMESH.cpp
Src/ModelLoadVBO.cpp

A few minor feature requests and some other workflows I have made me revisit the Model loader APIs. This collapses the two defaulted ``bool`` values into a flags field.
Also added two features:
* Allowing models that are larger than the 'required resource support size' constants for Direct3D
* Converting material color information in ``CMO`` and/or ``SDKMESH`` from sRGB colorspace to linear.
> Breaking change to ``Model::CreateFrom*`` methods but it's easy to fix up if you passed a non-default bool value.

Added ModelLoaderFlags

---

Audio/DirectXTKAudio_Desktop_2017_DXSDK.vcxproj
Audio/DirectXTKAudio_Desktop_2017_DXSDK.vcxproj.filters
Audio/DirectXTKAudio_Desktop_2017_Win7.vcxproj
Audio/DirectXTKAudio_Desktop_2017_Win7.vcxproj.filters
Audio/DirectXTKAudio_Desktop_2017_Win8.vcxproj
Audio/DirectXTKAudio_Desktop_2017_Win8.vcxproj.filters
Audio/DirectXTKAudio_Desktop_2019_Win7.vcxproj
Audio/DirectXTKAudio_Desktop_2019_Win7.vcxproj.filters
Audio/DirectXTKAudio_Desktop_2019_Win8.vcxproj
Audio/DirectXTKAudio_Desktop_2019_Win8.vcxproj.filters
Audio/SoundCommon.h
Audio/SoundStreamInstance.cpp
Audio/WaveBank.cpp
Audio/WaveBankReader.cpp
CMakeLists.txt
DirectXTK_Desktop_2017_Win10.vcxproj
DirectXTK_Desktop_2017_Win10.vcxproj.filters
DirectXTK_Desktop_2019_Win10.vcxproj
DirectXTK_Desktop_2019_Win10.vcxproj.filters
DirectXTK_Windows10_2017.vcxproj
DirectXTK_Windows10_2017.vcxproj.filters
DirectXTK_Windows10_2019.vcxproj
DirectXTK_Windows10_2019.vcxproj.filters
DirectXTK_XboxOneXDK_2017.vcxproj
DirectXTK_XboxOneXDK_2017.vcxproj.filters
Inc/Audio.h
Src/Mouse.cpp

*DirectX Tool Kit for Audio* feature for supporting 'streaming' XACT3-style WaveBanks.
This supports PCM, ADPCM, and xWMA encoded wavebanks.
> This implementation does not support loop-points.

SoundStreamInstance for playing streaming wavebanks

---

.nuget/directxtk-config.cmake.in
CMakeLists.txt

This PR updates the CMake support in DirectX Tool Kit to support ``find_package(directxtk CONFIG)``:
```
find_package(directxtk CONFIG REQUIRED)
target_link_libraries(foo Microsoft::DirectXTK)
```

CMake package support 

---

CMakeLists.txt
Inc/Audio.h
Inc/BufferHelpers.h
Inc/DDSTextureLoader.h
Inc/DirectXHelpers.h
Inc/Effects.h
Inc/GeometricPrimitive.h
Inc/GraphicsMemory.h
Inc/Model.h
Inc/PostProcess.h
Inc/PrimitiveBatch.h
Inc/ScreenGrab.h
Inc/SimpleMath.h
Inc/SpriteBatch.h
Inc/SpriteFont.h
Inc/VertexTypes.h
Inc/WICTextureLoader.h
Inc/XboxDDSTextureLoader.h
Src/pch.h
XWBTool/xwbtool.cpp

Reviewed all the C++ standard library header usage and normalized usage for improved conformance.
* ``size_t`` requires ``cstddef``
* ``memcpy``, ``memcpy_s`` is officially in ``cstring``
* Use ``cassert`` instead of ``assert.h``
> The non-standard malloc.h is still being included for ``_aligned_malloc`` / ``_aligned_free``. To be conformant, I should update it to use ``aligned_alloc`` and ``free`` when building for C++17 which is in ``cstdlib``.
Also trimmed trailing whitespace in these files.

Code review for standard library header usage

---

Audio/DynamicSoundEffectInstance.cpp
Audio/SoundCommon.cpp
Audio/SoundCommon.h
Audio/SoundEffectInstance.cpp
Audio/SoundStreamInstance.cpp
Audio/WaveBankReader.cpp
Inc/Audio.h

* ``EnableDefaultMultiChannel`` helper method added to AudioEmitter to simplify multi-channel positional audio setup
* ``Apply3D`` method should take X3DAUDIO_LISTENER / X3DAUDIO_EMITTER without requiring the helper AudioListener/AudioEmitter structs
* ``GetChannelCount`` added to DynamicSoundEffectInstance, SoundEffectInstance, and SoundStreamInstance to simplify use of EnableDefaultMultiChannel method

Added AudioEmitter helper method for multi-channel emitter setup

---

Inc/PostProcess.h
Src/Shaders/ToneMap.fx
Src/Shaders/Utilities.fxh
Src/ToneMapPostProcess.cpp

Updated ToneMapPostProcess to allow dynamic control over the color primary rotation matrix used for HDR10 signal processing. It defaults to using the 'standard' Rec.709 to Rec.2020 color primary rotation just as before. This adds a ``SetColorRotation`` method with an overloads.

ToneMapPostProcess updated with color rotation transform control

---

DirectXTK_Desktop_2017_Win7.sln
DirectXTK_Desktop_2019_Win7.sln
Inc/Effects.h
Inc/GeometricPrimitive.h
Src/DebugEffect.cpp
Src/GeometricPrimitive.cpp
Src/NormalMapEffect.cpp
Src/PBREffect.cpp
Src/Shaders/CompileShaders.cmd
Src/Shaders/DebugEffect.fx
Src/Shaders/NormalMapEffect.fx
Src/Shaders/PBREffect.fx
Src/Shaders/Structures.fxh
Src/Shaders/Utilities.fxh

* DebugEffect, NormalMapEffect, PBREffect updated to support instancing using a XMFLOAT3X4 transform in the vertex data.
* Added DrawInstanced method to GeometricPrimitive
> These effects all require Direct3D Feature Level 10.0 or better as they build with Shader Model 4.0, and all such devices support hardware instancing.

DebugEffect, NormalMapEffect, PBREffect updated with instancing support

---

Inc/Model.h
README.md
Src/Model.cpp
Src/ModelLoadCMO.cpp
Src/ModelLoadSDKMESH.cpp
Src/PlatformHelpers.h

Adds the **ModelBone** class to *DirectX Tool Kit*'s **Model** support, with loading from ``SDKMESH`` and ``CMO`` files.
* Includes the bone transforms and inverse bind pose transforms needed for both rigid-body and skinned animation.
* The ``ModelLoader_IncludeBones`` flag must be specified to have the loaders include the bone information if present.
* The CMO loader optionally returns the offset into the file where animation clips are located for later processing.
**ModelMeshPart** updated with optional bone index for rigid-body animation, and optional bone-influences for indirect vertex mapping for bones (used by ``SDKMESH``).
**Model** updated with **Draw** method overload for rigid-body transform drawing.
**Model** and **ModelMeshPart** updated with **DrawSkinned** method.
**Model** …

Adding ModelBone support for transform hierarchies

---

Audio/SoundStreamInstance.cpp
Audio/WaveBank.cpp
Audio/WaveBankReader.cpp
Audio/WaveBankReader.h
Inc/Audio.h
XWBTool/xwbtool.cpp

*DirectX Tool Kit for Audio* wavebank streaming updated to support Advanced Format (4Kn) format drives which have a 4096 sector size vs. the classic 2048 that worked for DVDs, older generation HDDs, and Advanced Format drives in 512e mode.

WaveBank streaming updated to support Advanced Format (4Kn)

---

Inc/SimpleMath.h
Inc/SimpleMath.inl

This adds a ``ToEuler`` method to both Matrix and Quaternion that returns a Vector3 with the x-axis, y-axis, and z-axis rotations required to create the rotation.
This uses the same rotational order as the yaw-pitch-roll functions which is "rotates about y-axis (yaw), then x-axis (pitch), then z-axis (roll)"
Also added overloads of the ``CreateFromYawPitchRoll`` methods for both Matrix and Quaternion that takes the angles as a Vector3 in the same order.

Added ToEuler methods to Matrix and Quaternion

---

Inc/SimpleMath.h
Inc/SimpleMath.inl
Src/SimpleMath.cpp

SimpleMath was based on the methods in the XNA Game Studio math classes. There are a few Quaternion functions that have been added to other math libraries that would be useful to add for Quaternion:
* ``RotateTowards`` which moves a quaternion toward a target quaternion limited by a maximum delta angle
* ``FromToRotation`` which computes a relative rotation between two direction vectors
* ``LookRotation`` which computes a rotation which aligns to a direction and up vector
* ``Angle`` which computes the angle between two quaternion rotations

Add more Quaternion methods for SimpleMath

---

Audio/WAVFileReader.cpp
Audio/WaveBankReader.cpp
Src/BinaryReader.cpp
Src/LoaderHelpers.h
Src/ScreenGrab.cpp
Src/WICTextureLoader.cpp
Src/XboxDDSTextureLoader.cpp
XWBTool/xwbtool.cpp

Per the C++ Standard:
> the identifiers that begin with an underscore followed by an uppercase letter are reserved;
I had this in my backlog for some time, but never got around to it until now. Clang v13 (which is in VS 2022 Update 1) has added a new warning for this case: ``-Wreserved-identifier``

Convert internal functions to use Internal namespace instead of leading underscore

---

Audio/AudioEngine.cpp
Inc/GamePad.h
Inc/Keyboard.h
Inc/Mouse.h
Src/GamePad.cpp
Src/Keyboard.cpp
Src/Mouse.cpp
Src/pch.h

* Cleaned up the code a bit to simplify the various ``#if`` conditions
* Added ``WM_ACTIVATE`` to Win32 Keyboard
* Added ``Mouse::SetWindow`` and ``Keyboard::ProcessMessage`` methods for GameInput implementation to simplify integration instructions
* Fixed bug with UWP Mouse so it doesn't track the HWHEEL as the normal WHEEL
* Legacy Xbox One XDK support now requires April 2018, May 2018, or June 2018.

Input refactoring and cleanup

---

DirectXTK_GDK_2019.sln
DirectXTK_GDK_2019.vcxproj
DirectXTK_GDK_2019.vcxproj.filters
DirectXTK_GDK_2022.sln
DirectXTK_GDK_2022.vcxproj
DirectXTK_GDK_2022.vcxproj.filters
Src/pch.h

The Gaming.Desktop.x64 Platform is part of the [Microsoft GDK](https://github.com/microsoft/GDK). For Xbox, DirectX 12 is required, but for PC either DirectX 11 or DirectX 12 are supported.
This is effectively a variant of the **DirectXTX_Desktop_*_Win10** project.

Add GDK projects for Gaming.Desktop.x64 only

---

Src/Shaders/CompileShaders.cmd

user account containing 'firstName + whitespace + lastName'. It will build fails
> Generating HLSL shaders... 'Lastname' is not recognized as an internal or external command, operable program or batch file
see https://github.com/xmake-io/xmake/issues/2714#issuecomment-1226666813

Fix path issue with spaces

---

CMakeLists.txt
Inc/BufferHelpers.h
Inc/CommonStates.h
Inc/DDSTextureLoader.h
Inc/DirectXHelpers.h
Inc/Effects.h
Inc/GeometricPrimitive.h
Inc/GraphicsMemory.h
Inc/Model.h
Inc/PostProcess.h
Inc/PrimitiveBatch.h
Inc/SpriteBatch.h
Inc/SpriteFont.h
Inc/VertexTypes.h
Inc/WICTextureLoader.h
README.md
Src/BufferHelpers.cpp
Src/PrimitiveBatch.cpp
Src/ScreenGrab.cpp
Src/WICTextureLoader.cpp

This adds use of C++11 inline namespaces to wrap types that have *DirectX Tool Kit for DX12* equivalents with the same name. This would allow for 'mixed' use of the *DirectX Tool Kit for DX11* and *DirectX Tool Kit for DX12* in the same exe without link-time conflicts.
It has no client-code impacts, although all client code would need rebuilt to link against a static library build with these changes.

Add use of C++11 inline namespaces

---

Inc/GamePad.h
Inc/Keyboard.h
Inc/Mouse.h
Src/GamePad.cpp
Src/Keyboard.cpp
Src/Mouse.cpp

By default the input implementation choice is made by the platform defines. This allows the ``USING_GAMEINPUT``, ``USING_WINDOWS_GAMING_INPUT``, and ``USING_XINPUT`` defines to override this rather than just indicating the choice.
The defines can also be used to force the header when used in client code to match whatever choice was used to build the library in cases where the defaults don't match.

Added explicit GAMEINPUT vs. WGI vs. XINPUT preprocessor overrides

---

CMakeLists.txt

The ``/Zc:inline`` switch enforces C++11 rules on inline visibility which reduces redundant comdats in each OBJ file (i.e. all the DirectXMath inline functions you *didn't* call in that translation unit). This switch is on by default with MSBuild, but is *not* on by default for command-line builds. This update adds this switch to CMake builds as well.
This reduces the size of the Release obj/lib files in half.
There's also a ``/Zc:lambda`` conformance switch for VS 2019 16.8 or later which I'm enabling for coverage.

CMake updated to use /Zc:inline and /Zc:lambda 

---

CMakeLists.txt
build/DirectXTK-GitHub-WSL-11.yml
build/DirectXTK-GitHub-WSL.yml

Update the WSL build pipelines to validate both Debug and Release configurations for SimpleMath.
In addition, this PR introduces a new CMake build option ``DISABLE_MSVC_ITERATOR_DEBUGGING`` to allow clients to disable MSVC's iterator debugging in Debug configuration since this is now the 'default' for clang/LLVM for Windows builds even when not using the ``clang-cl`` driver.

Test Debug and Release for WSL YAML

---

.nuget/directxtk_desktop_2019.nuspec
Audio/DirectXTKAudio_Desktop_2019_Win7.vcxproj
Audio/DirectXTKAudio_Desktop_2022_Win7.vcxproj
Audio/packages.config
CMakePresets.json
build/DirectXTK-GitHub-MinGW.yml

Update for latest XAudio2Redist NuGet release. 1.2.11 includes bug fixes to make the headers link correctly when using the MinGW toolset.

Update for XAudio2Redist 1.2.11

---

Src/DDSTextureLoader.cpp
Src/LoaderHelpers.h

Added height alignment validation for planar video formats. This reports these issues earlier as NOT_SUPPORTED instead of the E_INVALIDARG error that is eventually returned from the Direct3D API.

Additional checks for video formats for DDSTextureLoader

---

Inc/Mouse.h
Src/Mouse.cpp

For high-sensitivity mice, ``WM_INPUT`` is getting called multiple times per frame and the original implementation of RAW mouse for Win32 was only recording the most recent dx/dy. This change now accumulates delta from ``WM_INPUT`` in relative mode.
For this to work correctly, each time ``Mouse::GetState`` is called in relative movement mode, the accumulated delta is reset so the assumption is that this is called _once per frame_.
Since this does not cover all usage scenarios, there is new optional method for Mouse **EndOfInputFrame** that should be called once per render call. This turns off the 'auto-reset' behavior of **GetState** and instead clears it once per frame in this method instead.

Mouse needs to accumulate delta between calls to GetState

---

Audio/AudioEngine.cpp
Inc/Audio.h

XAudio 2.8 on Windows 8 required the use of Windows Runtime APIs for device enumeration. XAudio2.9 on Windows 10 (18362)  or later and all versions of XAudio2Redist support both Windows Runtime device ids -and- standard WASAPI device ids.
This PR reworks the device enumeration to use WASAPI enumeration for most cases, and WinRT enumeration for the UWP platform and for XAudio 2.8 scenarios only.
In addition, this PR returns correct values for ``GetOutputFormat().Format.wBitsPerSample`` where possible. It previously always returned a value of 16.
> For Windows Server 2019 (17763) or other older Windows 10 scenarios, the recommendation is to use XAudio2Redist instead of the built-in XAudio 2.9.

Rework audio device enumeration for XAudio2.9

---

Audio/AudioEngine.cpp
XWBTool/xwbtool.cpp
XWBTool/xwbtool_Desktop_2019.vcxproj
XWBTool/xwbtool_Desktop_2022.vcxproj

The **xwbtool** tool is a Windows command-line tool, and so doesn't follow POSIX utility conventions. This PR, however, adds support for a few specific behaviors:
```
xwbtool --version
```
```
xwbtool --help
```
All paths read from the command-line or from *-flist* files are normalized to the Windows path separator, so the tool now accepts UNIX-style paths or Windows-style paths. In order to allow the input filenames to start with a `/`, you can use `--` as an escape to indicate the 'end of options' which will allow input filenames to start with either `-` or `/`.
```
xwbtool [options] -- /folder/path/to/name/fname.obj
```
> This PR also makes the command-line tool build using C++17 mode.

xwbtool updates for some POSIX like support

---

CMakeLists.txt
CMakePresets.json
Inc/DirectXHelpers.h
Inc/Keyboard.h
Inc/SimpleMath.h
README.md

The XBOX_CONSOLE_TARGET variable can be set to ``durango`` if built in the appropriate Developer Command Prompt.
> Can't support ``scarlett`` or ``xboxone`` as those require DirectX 12. While I've officially dropped legacy Xbox One XDK support for this library, there are still some backcompat scenarios I need to support.
Also added some warning suppressions for the clang v16 toolset.

CMake support for building legacy Xbox One XDK lib

---

.nuget/directxtk_desktop_2019.nuspec
.nuget/directxtk_desktop_win10.nuspec
.nuget/directxtk_uwp.nuspec
HISTORY.md
README.md

* MapGuard in DirectXHelpers should not support the move ctor or move operator
* CMake project updates and fixes for clang/LLVM v16 warnings
* xwbtool: Windows on ARM64 version

April 28, 2023

---

CMakeLists.txt
XWBTool/settings.manifest
XWBTool/xwbtool.cpp
XWBTool/xwbtool_Desktop_2019.vcxproj
XWBTool/xwbtool_Desktop_2019.vcxproj.filters
XWBTool/xwbtool_Desktop_2022.vcxproj
XWBTool/xwbtool_Desktop_2022.vcxproj.filters

Updates **xwbtool** to support very long file names with Windows 10 (Version 1607) or later.
> Note that the tool does not support UNC style ``\\?\`` long paths as those are not supported by ``std::filesystem``.

xwbtool updated to support long path names with Windows 10

---

build/DirectXTK-config.cmake.in

The CMakeLists.txt no longer mandates the **directxmath** package be found unless building with MinGW. This fixes the behavior for CMake clients consuming this package from VCPKG.

CMake target file fix

---

build/DirectXTK-config.cmake.in

With the changes to make use of DirectXMath 'optional' for VCPKG scenarios unless using MinGW, the generated targets file needed more robust handling of these targets.

CMake targets fixes for optional vs. required packages

---

Audio/AudioEngine.cpp
Audio/SoundEffect.cpp
Audio/WaveBank.cpp
CMakeLists.txt
Inc/Audio.h
Inc/Effects.h
Inc/GeometricPrimitive.h
Inc/Model.h
Inc/PostProcess.h
Inc/ScreenGrab.h
Inc/SpriteBatch.h
Inc/SpriteFont.h
Src/BasicPostProcess.cpp
Src/DDSTextureLoader.cpp
Src/DualPostProcess.cpp
Src/ModelLoadCMO.cpp
Src/ModelLoadSDKMESH.cpp
Src/ModelLoadVBO.cpp
Src/ScreenGrab.cpp
Src/SpriteFont.cpp
Src/ToneMapPostProcess.cpp
Src/WICTextureLoader.cpp
build/DirectXTK-GitHub-CMake-Dev17.yml
build/DirectXTK-GitHub-CMake.yml

Some usage scenarios build the library with ``/Zc:wchar_t-`` but mix both ``unsigned short*`` and ``wchar_t*`` client usage. For this *opt-in* build scenario, the library will link with both the non-native and native ``wchar_t``.
Note this works for general use, but not necessarily all use cases. For example, all the effect factory virtual methods are defined only using the type that matches the compiler setting for the library, as there's no easy way to provide an adapter for these. There are also some edge-cases like ``SpriteFont::GetDefaultCharacter`` that you can't use a link-time adapter because the overloading rules don't allow only differing by return type.
> Also fixes some Code Analysis warnings as you can't use ``_In_opt_`` with ``std::function<>`` or ``std::shared_ptr<>``.

Add NO_WCHAR_T build option to CMake

---

Src/pch.h

The CMake scenario already disables the new clang v16 warning, but if you upgrade the VCXPROJ project to clangcl, it reappears.

Suppress some additional clang v16 warnings when upgrading to clangcl

---

.nuget/directxtk_uwp.nuspec
CMakePresets.json
DirectXTK_Windows10_2019.sln
DirectXTK_Windows10_2019.vcxproj
DirectXTK_Windows10_2022.sln
DirectXTK_Windows10_2022.vcxproj
build/DirectXTK-GitHub-CMake-Dev17.yml
build/DirectXTK-GitHub-CMake.yml
build/DirectXTK-GitHub-Dev17.yml
build/DirectXTK-GitHub-SDK-prerelease.yml
build/DirectXTK-GitHub-SDK-release.yml
build/DirectXTK-GitHub-Test.yml
build/DirectXTK-GitHub.yml
build/Directory.Build.props

32-bit ARM support is being deprecated for the UWP platform, and support is being removed from newer ARM-based CPUs and the Windows 11 OS.
> 32-bit ARM was never officially supported for Win32 desktop development.
See [Microsoft Learn](https://learn.microsoft.com/windows/arm/arm32-to-arm64)

AArch32 (ARM32) architecture deprecation

---

Audio/SoundCommon.cpp
Inc/Audio.h

Added *EnableLinearCurves* and *EnableInverseSquareCurves* helpers. *EnableDefaultCurves* still work as before turning off distance attenuation as it does in XACT.

Additional curve helpers for AudioEmitter

---

build/DirectXTK-GitHub-MinGW.yml
build/DirectXTK-GitHub-Test-Dev17.yml

The latest **windows-2022** ADO image no longer includes the Ninja build tool by default. It had been pulled in by another component as a dependency but is no longer there. The official solution is to install ninja using the Chocolatey package manager which part of the base image.
The latest update upgraded MinGW-W64 to 12.2, so I no longer need to explicitly install it for that pipeline.

Update build pipelines for recent changes to windows-2022 ADO images

---

XWBTool/xwbtool.cpp

The file list processing failed with filenames with spaces in them. This fixes the parsing to be line-by-line explicitly.

Fixed -flist handling for filenames with spaces

---

Audio/WAVFileReader.cpp

When looking at a RIFF/IFF FORM, the containing chunk size includes the 4 bytes of the FORM tag. This fixes the bounds computation to take this into account.

RIFF parsing bounds fix for WAVFileReader

---

build/DirectXTK-OneFuzz.yml

In #422 the output directory of CMake was updated, so the OneFuzz pipeline need adjustment to match.

OneFuzz ADO pipeline adjustments

---

DirectXTK_GDK_2019.vcxproj
DirectXTK_GDK_2022.vcxproj
build/DirectXTK-GitHub-WSL-11.yml
build/DirectXTK-GitHub-WSL.yml
build/DirectXTK-OneFuzz.yml

* Added a target to the GDK projects to provide a more actionable error message in the case of the GDK not being installed -or- the VS integration is missing.
* Updated YAML because the `-o` parameter is ambiguous for modern PowerShell.

Update GDK projects and ADO pipelines

---

Audio/AudioEngine.cpp
Audio/DynamicSoundEffectInstance.cpp
Audio/SoundStreamInstance.cpp
Audio/WaveBankReader.cpp
Inc/Audio.h
Inc/DirectXHelpers.h
Inc/GamePad.h
Inc/Keyboard.h
Inc/Mouse.h
Inc/ScreenGrab.h
Inc/WICTextureLoader.h
Src/GamePad.cpp
Src/GraphicsMemory.cpp
Src/Keyboard.cpp
Src/Mouse.cpp
Src/PlatformHelpers.h
Src/pch.h
XWBTool/xwbtool.cpp

Guard pragmas specific to MSVC-like compilers

fix warning for MSVC pragma syntax

---

build/DirectXTK-GitHub-Test.yml

Fix failure with GitHub test pipeline

---

XWBTool/xwbtool_Desktop_2019.vcxproj
XWBTool/xwbtool_Desktop_2022.vcxproj

The `/CETCOMPAT` linker flag is already enabled for EXEs build by VS 2022, but is also supported by VS 2019 (16.11) via `AdditionalOptions`.

Enable /CETCOMPAT when building with VS 2019

---

build/CompilerAndLinker.cmake
build/DirectXTK-GitHub-Dev17.yml
build/DirectXTK-GitHub-GDK-Dev17.yml
build/DirectXTK-GitHub-Test-Dev17.yml
build/DirectXTK-GitHub-WSL-11.yml

* GNU still defaults to x87 math code-gen on x86, so this opts into SSE/SSE2 math generation.

Update compiler build settings for CMake

---

Src/ScreenGrab.cpp
Src/WICTextureLoader.cpp

I used the ``DirectX::Internal`` namespace in some other contents, and in particular I used an inline namespace ``DirectX::DX11`` with an ``Internal`` namespace. This confuses some compilers and resulted in build failures. As a solution, I just renamed the internal namespaces to something more unique.

Rename Internal namespace to ToolKitInternal for some conformance issues

---

.nuget/directxtk_desktop_2019.nuspec
.nuget/directxtk_desktop_win10.nuspec
.nuget/directxtk_uwp.nuspec
CHANGELOG.md
README.md

* Renamed Internal namespace to ToolKitInternal for some conformance issues
* CMake project updates
* Retired VS 2019 projects for the UWP platform

June 4, 2024

---

.github/workflows/codeql.yml
.github/workflows/main.yml
.github/workflows/msbuild.yml
.github/workflows/msvc.yml
.github/workflows/test.yml
CMakePresets.json
build/DirectXTK-GitHub-CMake-Dev17.yml
build/DirectXTK-GitHub-CMake.yml
build/DirectXTK-GitHub-Dev17.yml
build/DirectXTK-GitHub-GDK.yml
build/DirectXTK-GitHub-MinGW.yml
build/DirectXTK-GitHub-Test-Dev17.yml
build/DirectXTK-GitHub-Test.yml
build/DirectXTK-GitHub.yml
build/DirectXTK-SDL.yml

While most pipelines are hosted on ADO, this adds GitHub build actions that are available to everyone who forks the repo. This also uses GitHub actions to validate PRs where possible rather than ADO for security reasons.
Also enables the GitHub Action based CodeQL and PREfast analysis.

Added GitHub Actions for build and security analysis

---

Audio/SoundCommon.cpp
Inc/Audio.h

X3DAudio requires only 'real' values for floats, so values like INF or NAN will cause runtime faults. This PR adds an ``IsValid`` method that can be used on emitter and listener as part of a debug assert to check for these conditions.
This also provided a place to add additional validation of ranges for listener curves on emitters, as well as validate pChannelAzimuths usage.

IsValid methods for AudioEmitter and AudioListener

---

DirectXTK_Desktop_2019.vcxproj
DirectXTK_Desktop_2019_Win10.vcxproj
DirectXTK_Desktop_2022.vcxproj
DirectXTK_Desktop_2022_Win10.vcxproj
DirectXTK_GDK_2019.vcxproj
DirectXTK_GDK_2022.vcxproj
DirectXTK_Windows10_2022.vcxproj

Since CompileShaders might need ``WindowsSDKVersion`` this update passes that through.

Update BWOI support in VC projects

---

.github/dependabot.yml
.github/workflows/vcpkg.yml
CMakeLists.txt
build/DirectXTK-GitHub-GDK.yml
build/DirectXTK-GitHub-MinGW.yml
build/DirectXTK-GitHub-Test-Dev17.yml
build/DirectXTK-GitHub-Test.yml
build/DirectXTK-GitHub-WSL-11.yml
build/DirectXTK-GitHub-WSL.yml
build/DirectXTK-OneFuzz-Coverage.yml
build/DirectXTK-OneFuzz.yml
build/DirectXTK-SDL.yml
build/vcpkg.json

This PR makes sure ``assert`` macros in the library built for fuzz-testing remain in place even in release builds.
> Includes ADO YAML code review to clean up use of PATs, and to convert all use of vcpkg in the pipelines to 'manifest mode'.
> Also sets the dependabot to not spam quite so often for GHA.

Keep asserts on in fuzz-testing builds

---

Inc/DDSTextureLoader.h
Src/DDSTextureLoader.cpp

Adds a flag option to DDSTextureLoader for only loading the first mip of a DDS file.
> This was added to DirectXTex as `DDS_FLAGS_IGNORE_MIPS` in July. It is useful for more than just corrupted files.

Add DDS_LOADER_IGNORE_MIPS flag to DDSTextureLoader

---

XWBTool/xwbtool.cpp

Fixes warning when building with VS 2022 17.12 with clang v18.1.8

Fix -Wunused-member-function warning in xwbtool

---

README.md
build/DirectXTK-GitHub-SDK-prerelease.yml
build/DirectXTK-GitHub-SDK-release.yml

As of Windows SDK version 10.0.26100.1834, ARM64 for Win32 "classic" Desktop no longer builds with the VS 2019 toolset. VS 2022 is required.

VS 2019 Win32 on ARM64 is no longer supported

---

Inc/Audio.h
Inc/DDSTextureLoader.h
Inc/Effects.h
Inc/GamePad.h
Inc/Model.h
Inc/Mouse.h
Inc/PostProcess.h
Inc/SpriteBatch.h
Inc/WICTextureLoader.h

Originally I used `DWORD` for flags. When I removed Windows-specific types, I changed it to `unsigned long` to keep the signature the same. The ask is to use `uint32_t` instead which is more consistent on Windows vs. Linux.
Also removed 'extra-semi' for macro.

Use fixed width integers for underlying enum types

---

MakeSpriteFont/CommandLineParser.cs
XWBTool/xwbtool.cpp

Embraces the `-so` vs. `--long-option` GNU-like pattern for the command-line tool.
This also adds `-o=value` which is the GNU standard and the tool already supported `-o:value` or `-o value`.
> This is a hybrid of the Windows style and GNU-like pattern. For example, you can't combine single-characters together such as  `-yl` with this tool like you can with GNU-style argument syntax. Not all multi-character options use `--` which would be the GNU standard.
> The tool already supports the `-- ` escape so you can start filenames with `/` or `-`

Convert xwbtool to use GNU-style long options

---

CMakeLists.txt
Inc/DDSTextureLoader.h
Inc/Model.h
Inc/WICTextureLoader.h
Inc/XboxDDSTextureLoader.h

When #497 was added to make the type of `FromMemory` operations use something other than `void*`, this turns out to result in code-breaks for clients using C++17's ``std::byte*``.
This PR adds compat inlines to avoid requiring the client code add casts.
> Minor tweak to CMake to avoid requiring all clients use the directxmath package externally.

Support using C++17 std::byte for FromMemory functions

---

CMakeLists.txt

For Win32 scenarios, DirectXMath is optional for building. Even when using that package is used to build the library, the client code can still choose to use the SDK version of those headers which works fine.
For MinGW, however, clients must always use the packages since the platform toolset don't include these headers (or at least not the right versions of them).

Fix for CMake using MinGW

---

Audio/SoundCommon.h
Src/LoaderHelpers.h

I added some 'whitebox' testing of internal functions and it was resulting in link failures in some cases due to inconsistent calling conventions for the internal linkage. This decorates the internal free-functions for DirectX Tool Kit for Audio to make this linking robust.
> Also includes a minor update to use E_INVALIDARG

Minor update to enable 'white box' testing of some internal functions

---

Audio/SoundCommon.cpp
Audio/SoundStreamInstance.cpp
Src/AlphaTestEffect.cpp
Src/Geometry.cpp
Src/LoaderHelpers.h
Src/ModelLoadCMO.cpp
Src/ModelLoadSDKMESH.cpp
Src/ModelLoadVBO.cpp
Src/Mouse.cpp
Src/SharedResourcePool.h
Src/SpriteBatch.cpp
Src/SpriteFont.cpp
Src/WICTextureLoader.cpp
build/DirectXTK-GitHub-WSL-13.yml

Both ``const auto`` and ``auto const`` are equivalent in terms of the C++ compiler parser, but general coding guidelines suggest using ``const auto``. The primary reason for this PR is to be consistent since the codebase was using both.

Code review for const auto vs auto const

---

build/DirectXTK-GitHub-WSL-13.yml

The codegen bug with GCC v11 optimization of SimpleMath that resulted in disabling a test in #348 is still present in GCC 13.

disable release test for SimpleMath GNU v13

---

build/DirectXTK-GitHub-CMake.yml
build/DirectXTK-GitHub-Test-Dev17.yml
build/DirectXTK-GitHub-Test.yml
build/DirectXTK-GitHub.yml

Remove cases of building for ARM64 with VS 2019 due to changes to Windows SDK (26100).
Also cleans up the original #436 quick fix for UWP which should be building in the Dev17 pipeline.

Update ADO coverage for clang v12 

---

Inc/SimpleMath.h
Inc/SimpleMath.inl

* Fixed regression in #539 with Vector2/Vector3 * operator with scalar float first.
* added `operator/(scalar, vector)` for Vector2, Vector3, Vector4
* added `operator/(scalar, matrix)` for Matrix
* some minor code review

SimpleMath fixes for binary operator* with scalar

---

Audio/AudioEngine.cpp
Audio/SoundCommon.cpp
Audio/SoundCommon.h
Inc/Audio.h

* Adds new audio engine flags
* `AudioEngine_DisableLFERedirect` will disable the current default behavior of using `X3DAUDIO_CALCULATE_REDIRECT_TO_LFE` if there is a LFE channel in the output.
* `AudioEngine_DisableDopplerEffect` will disable the current default use of  `X3DAUDIO_CALCULATE_DOPPLER` for all X3DAudio calculations.
* `AudioEngine_ZeroCenter3D` will add `X3DAUDIO_CALCULATE_ZEROCENTER` to all X3DAudio calculations.
* Adds new sound instance flags
* `SoundEffectInstance_UseRedirectLFE` internal flag now repurposed to force use of `X3DAUDIO_CALCULATE_REDIRECT_TO_LFE` per voice if not enabled globally and if there is a LFE channel in the output.
* `SoundEffectInstance_ZeroCenter3D` flag forces the use of  `X3DAUDIO_CALCULATE_ZEROCENTER` per voice if not enabled globally.

Improve control for X3DAudio calculate flags

---

.azuredevops/policies/approvercountpolicy.yml
Audio/SoundCommon.h
Inc/Audio.h
Inc/BufferHelpers.h
Inc/CommonStates.h
Inc/DDSTextureLoader.h
Inc/DirectXHelpers.h
Inc/Effects.h
Inc/GamePad.h
Inc/GeometricPrimitive.h
Inc/GraphicsMemory.h
Inc/Keyboard.h
Inc/Model.h
Inc/Mouse.h
Inc/PostProcess.h
Inc/PrimitiveBatch.h
Inc/ScreenGrab.h
Inc/SimpleMath.h
Inc/SpriteBatch.h
Inc/SpriteFont.h
Inc/VertexTypes.h
Inc/WICTextureLoader.h
Inc/XboxDDSTextureLoader.h

CoPilot suggested a change which I disagreed with, but when I researched it a bit I realized there was a different change that would be useful to prefer `__attribute__` to `__declspec` for GNUC.
> Also includes some AzureDev Ops polices from the production pipelines.

Code review feedback for DLL declimport/export

---

.azuredevops/pipelines/DirectXTK-OneFuzz-Audio.yml
.azuredevops/pipelines/DirectXTK-OneFuzz-Meshes.yml

OneFuzz runs on the 1st of the month seeding DDS files.
OneFuzz runs on the 10th of the month seeding WAV and XWB files.
OneFuzz runs on the 20th of the month seeding CMO, SDKMESH, and VBO files.
All runs go for a week.

Add more OneFuzz pipelines

---

.github/workflows/bvt.yml
README.md

While the majority of the test suite requires running locally to see the graphics output and to hear the audio, this PR sets up a subset of tests for automated Build Verification Tests (BVTs). This covers file I/O formats, basic creation of various classes in the library, and math functions.

Add GitHub Action for BVTs with subset of tests

---

Src/CMO.h
Src/ModelLoadCMO.cpp
Src/ModelLoadVBO.cpp
Src/vbo.h

Minor updates to make CMO.h and VBO.h useful for DirectXMesh and UVAtlas.

Update CMO and vbo headers

---

.github/workflows/bvt.yml
.github/workflows/main.yml
.github/workflows/test.yml
.github/workflows/vcpkg.yml
.github/workflows/win10.yml

Switched all impacted pipelines to use *windows-2022*, but I still make use of v142 toolset for validation of the "VS 2019 (16.11)" compiler.

GitHub Actions windows-2019 runner is being retired

---

Audio/SoundCommon.cpp
Audio/WaveBankReader.cpp
Src/ModelLoadCMO.cpp

The suppression syntax didn't seem to be the right one for the tooling. Modified the comments and ensured the justification string is long enough.

CodeQL suppression syntax fix

---

.azuredevops/pipelines/DirectXTK-GitHub-CMake.yml
.azuredevops/pipelines/DirectXTK-GitHub-GDK-Dev17.yml
.azuredevops/pipelines/DirectXTK-GitHub-GDK.yml
.azuredevops/pipelines/DirectXTK-GitHub-Test-Dev17.yml
.azuredevops/pipelines/DirectXTK-GitHub-Test.yml
.azuredevops/pipelines/DirectXTK-GitHub.yml
.github/copilot-instructions.md
.github/linters/actionlint.yml
.github/workflows/arm64.yml
.github/workflows/arm64bvt.yml
build/RestoreGDK.proj
build/RestoreGDK.ps1
build/SetupBWOI.cmd
build/gdkedition.props

* GitHub Actions using Windows on ARM64 native
* Updated Azure pipelines to stop using the windows-2019 image while still testing the v142 platform toolset.
* Some minor updates for the GDK pipelines for the package renaming as of October 2024.

GHA and ADO pipeline updates

---

.azuredevops/pipelines/DirectXTK-GitHub-CMake-Dev17.yml
.azuredevops/pipelines/DirectXTK-GitHub-CMake.yml
.azuredevops/pipelines/DirectXTK-GitHub-MinGW.yml
.azuredevops/pipelines/DirectXTK-OneFuzz-Audio.yml
.azuredevops/pipelines/DirectXTK-OneFuzz-Meshes.yml
.azuredevops/pipelines/DirectXTK-OneFuzz.yml
.github/copilot-instructions.md
.gitignore
Audio/SoundCommon.cpp
CMakeLists.txt
Inc/Audio.h
Inc/Keyboard.h
Src/BufferHelpers.cpp
Src/CommonStates.cpp
Src/EffectFactory.cpp
Src/GeometricPrimitive.cpp
Src/Keyboard.cpp
Src/PrimitiveBatch.cpp
Src/SpriteBatch.cpp
Src/SpriteFont.cpp

* Marked a few more functions as ``noexcept``
* Added more ``std::invalid_argument`` checks for null device to ctors
* Added `ENABLE_CODE_PROFILING` option to CMake
> windows-2022 image removed 10.0.22000.0 SDK

Code review and CoPilot instructions update

---

.github/workflows/bvt.yml
CMakeLists.txt
CMakePresets.json
README.md
Src/LoaderHelpers.h
Src/PlatformHelpers.h

CMake 3.21 comes with VS 2022.
> VS 2019 users will need to install a standalone version of a CMake newer than the 3.20 that comes with it.

Upgrade to CMake 3.21
