Inc/GamePad.h
Just like Menu/View alias for the other structs
=> View/Menu alias for GetState

Inc/DirectXHelpers.h, Src/GraphicsMemory.cpp
DirectXHelpers.h updated with public ``AlignUp`` and ``AlignDown`` helpers.
=> AlignUp, AlignDown helpers

Inc/SimpleMath.h, Inc/SpriteBatch.h, Src/AlignedNew.h, Src/Bezier.h, Src/DGSLEffectFactory.cpp, Src/EffectFactory.cpp, Src/Model.cpp, Src/ModelLoadSDKMESH.cpp, Src/PBREffect.cpp, Src/PBREffectFactory.cpp, Src/ScreenGrab.cpp, Src/SimpleMath.cpp
Trying out the code-base with a GNUC compiler I encountered a number of issues that I've cleaned up.
=> Conformance and minor code cleanup

Audio/SoundCommon.cpp, Inc/Audio.h
DirectX Tool Kit for Audio quality of life improvements for positional audio.
* Added ``SetCone`` and ``SetOmnidirectional`` methods to simplify use of directional cones
* Added ``EnableDefaultCurves`` method to simplify emitter setup.
=> More AudioEmitter / AudioListener methods

.nuget/directxtk_desktop_2019.nuspec, .nuget/directxtk_desktop_win10.nuspec, .nuget/directxtk_uwp.nuspec, HISTORY.md, README.md
* GamePad, Keyboard, and Mouse headers have ``USING_XINPUT``, ``USING_GAMEINPUT``, ``USING_WINDOWS_GAMING_INPUT`` defines
* Updates for *GameInputCreate* failure handling on PC
* *DirectX Tool Kit for Audio* updated for XAudio2Redist 1.2.10
* CMake project updated to require 3.20 or later
* CMake and MSBuild project updates
* Minor MinGW code changes
* Added Azure Dev Ops Pipeline YAML files
* Test suite updated with CTest support
=> December 15, 2022

.nuget/directxtk_desktop_2019.nuspec, .nuget/directxtk_desktop_win10.nuspec, .nuget/directxtk_uwp.nuspec, CMakeLists.txt, HISTORY.md, LICENSE, README.md
* Mouse relative mode now accumulates multiple delta updates per frame. Added new optional but recommended method ``EndOfInputFrame``.
* Fixed out-of-bounds read bug in the .WAV file reader.
* Additional checks added to DDSTextureLoader for planar video formats.
* *DirectX Tool Kit for Audio* updated for XAudio2Redist 1.2.11
* CMake project updates
=> February 6, 2023

LICENSE, README.md, SECURITY.md, build/DirectXTK-GitHub-CMake-Dev17.yml, build/DirectXTK-GitHub-CMake.yml, build/DirectXTK-GitHub-Dev17.yml, build/DirectXTK-GitHub-GDK-Dev17.yml, build/DirectXTK-GitHub-GDK.yml, build/DirectXTK-GitHub-MinGW.yml, build/DirectXTK-GitHub-SDK-prerelease.yml, build/DirectXTK-GitHub-SDK-release.yml, build/DirectXTK-GitHub-Test-Dev17.yml, build/DirectXTK-GitHub-Test.yml, build/DirectXTK-GitHub-WSL-11.yml, build/DirectXTK-GitHub-WSL.yml, build/DirectXTK-GitHub.yml
Update for latest files for MIT license and the SECURITY statement.
> Also tweaked CI/PR build triggers.
=> Update for latest files from the Microsoft GitHub template

Audio/AudioEngine.cpp
The **Resume** method threw a C++ exception if the XAudio2 StartEngine failed. It should switch to silent mode if it fails.
In addition, I added handling for the required audio device being 'locked' by exclusive mode ownership.
=> DirectX Tool Kit for Audio fix for failing Resume

.nuget/directxtk_desktop_2019.nuspec, .nuget/directxtk_desktop_win10.nuspec, .nuget/directxtk_uwp.nuspec, HISTORY.md, README.md
* *DirectX Tool Kit for Audio* updates
* Reworked audio device enumeration for XAudio 2.9 to use MMDeviceEnumerator rather than Windows Runtime APIs
* ``GetOutputFormat`` now reports sample rate and bit-depth from the audio device properties
* New method ``GetOutputSampleRate`` added to return the input sample rate of the mastering voice
* ``Resume`` now handles device failure by switching to silent mode
* CMake project updates
* Retired VS 2017 legacy Xbox One XDK projects
* xwbtool: Updated to support Windows or UNIX-style path separators
=> March 30, 2023

.nuget/directxtk_desktop_2019.nuspec, .nuget/directxtk_desktop_win10.nuspec, .nuget/directxtk_uwp.nuspec, HISTORY.md, README.md
* CMake project updates
* xwbtool: Fix minor display issue with error messages
* xwbtool: Supports Long Paths on Windows 10, Version 1607 or later
=> June 2023 release

Src/DDS.h, build/DirectXTK-GitHub-Dev17.yml, build/DirectXTK-GitHub-SDK-prerelease.yml, build/DirectXTK-GitHub-SDK-release.yml, build/DirectXTK-GitHub-Test-Dev17.yml, build/DirectXTK-GitHub-Test.yml, build/DirectXTK-GitHub.yml
Also includes a trivial update to ``DDS.h`` to match DirectXTex updates.
=> ADO build pipelines updated to space some working disk space

.gitignore, Audio/SoundCommon.cpp, Audio/WAVFileReader.cpp, Audio/WaveBankReader.cpp
Also includes some minor code review for DirectX Tool Kit for Audio.
=> Added more bounds checking to WAVFileReader

Audio/SoundStreamInstance.cpp, Audio/WaveBankReader.cpp, CMakeLists.txt, Src/ModelLoadCMO.cpp, Src/Mouse.cpp, build/DirectXTK-SDL.yml
=> Add SDL build pipeline

build/DirectXTK-GitHub-GDK.yml, build/DirectXTK-GitHub-MinGW.yml, build/DirectXTK-GitHub-Test-Dev17.yml, build/DirectXTK-GitHub-Test.yml, build/DirectXTK-GitHub-WSL-11.yml, build/DirectXTK-GitHub-WSL.yml, build/DirectXTK-OneFuzz.yml, build/DirectXTK-SDL.yml
* Use CodeQL 3000
* Minimize disk space usage for the cmake pipeline with tests
* YAML code review
=> Update ADO build pipelines

build/DirectXTK-GitHub-CMake-Dev17.yml, build/DirectXTK-GitHub-CMake.yml, build/DirectXTK-GitHub-GDK.yml, build/DirectXTK-GitHub-MinGW.yml, build/DirectXTK-GitHub-Test.yml, build/DirectXTK-GitHub-WSL.yml, build/DirectXTK-GitHub.yml, build/OneFuzzConfig.json
Connect pipeline in #439 to OneFuzz.
Also revisisted the various trigger/pr exclusion paths
=> Set code coverage pipeline for fuzzing

build/DirectXTK-GitHub-CMake-Dev17.yml, build/DirectXTK-GitHub-CMake.yml, build/DirectXTK-GitHub-GDK.yml, build/DirectXTK-GitHub-MinGW.yml, build/DirectXTK-GitHub-Test.yml, build/DirectXTK-GitHub-WSL.yml, build/DirectXTK-GitHub.yml
YAML updates in #440 were not correct.
=> Fix YAML synatx

Audio/AudioEngine.cpp, CMakeLists.txt, DirectXTK_Windows10_2022.vcxproj, README.md, Src/DDSTextureLoader.cpp, Src/GamePad.cpp, Src/WICTextureLoader.cpp, Src/pch.h, build/DirectXTK-GitHub-Dev17.yml, build/DirectXTK-GitHub-Test-Dev17.yml, build/DirectXTK-GitHub.yml, build/DirectXTK-SDL.yml
Adds use of ``/analyze`` to the SDL pipeline.
=> ADO pipeline changes for OpenSSF Best Practices

CMakePresets.json, build/DirectXTK-GitHub-Test-Dev17.yml
Adds ARM64EC presets per the instructions on [Microsoft Learn](https://learn.microsoft.com/en-us/windows/arm/arm64ec-build).
=> CMake updated to build ARM64EC

.github/workflows/publish.yml, build/DirectXTK-GitHub-CMake-Dev17.yml, build/DirectXTK-GitHub-CMake.yml, build/DirectXTK-GitHub-Dev17.yml, build/DirectXTK-GitHub-GDK-Dev17.yml, build/DirectXTK-GitHub-GDK.yml, build/DirectXTK-GitHub-SDK-prerelease.yml, build/DirectXTK-GitHub-SDK-release.yml, build/DirectXTK-GitHub-Test-Dev17.yml, build/DirectXTK-GitHub-Test.yml, build/DirectXTK-GitHub.yml, build/DirectXTK-SDL.yml
Various minor code review updates for ADO build pipelines.
Adds new publish GitHub action
=> Build pipeline updates

build/DirectXTK-GitHub-GDK-Dev17.yml, build/DirectXTK-GitHub-GDK.yml, build/DirectXTK-GitHub-SDK-prerelease.yml, build/DirectXTK-GitHub-SDK-release.yml, build/Directory.Build.props, build/SetupBWOI.targets
Includes some cleanup for BWOI scenarios
=> ADO pipeline for SDK builds

Src/Mouse.cpp
Sync's with a change submitted to *DirectX Tool Kit for DX12*.
=> Code review for Mouse CoreWindow implementation

build/DirectXTK-GitHub-WSL-11.yml, build/DirectXTK-GitHub-WSL-13.yml
Note this is only to validate SimpleMath on Linux using GCC.
> Also add a YAML for building with newer Ubuntu.
=> Fix some warnings in WSL build due to case

.nuget/directxtk_desktop_2019.nuspec, .nuget/directxtk_desktop_win10.nuspec, .nuget/directxtk_uwp.nuspec, Audio/AudioEngine.cpp, CHANGELOG.md, CMakeLists.txt, Inc/XboxDDSTextureLoader.h, README.md
* C++17 `std::byte` support for `FromMemory` functions
* GamePad, Keyboard, and Mouse _GameInput_ implementation now supports both v0 and v1 of the API
* SimpleMath changes for Vector2/Vector3 operators to speed up performance particularly in debug builds
* *DirectX Tool Kit for Audio* changes:
* Added more audio engine flags to control X3DAudio usage: `AudioEngine_DisableLFERedirect`, `AudioEngine_DisableDopplerEffect`, `AudioEngine_ZeroCenter3D`
* Repurposed `SoundEffectInstance_UseRedirectLFE` from an internal flag to a per voice override
* Added `SoundEffectInstance_ZeroCenter3D` as a per voice override
* Bug fixes for recent ``IsValid`` methods
* Retired support for Windows 7 and Windows 8.0
* Minor code review
* CMake project updates including support for BUILD_SHARED_LIBS (i.e. DLL …
=> March 20, 2025

.azuredevops/pipelines/DirectXTK-GitHub-Dev17.yml, .azuredevops/pipelines/DirectXTK-GitHub-GDK-Dev17.yml, .azuredevops/pipelines/DirectXTK-GitHub-GDK.yml, .azuredevops/pipelines/DirectXTK-GitHub-MinGW.yml, .azuredevops/pipelines/DirectXTK-GitHub-SDK-prerelease.yml, .azuredevops/pipelines/DirectXTK-GitHub-SDK-release.yml, .azuredevops/pipelines/DirectXTK-GitHub-Test-Dev17.yml, .azuredevops/pipelines/DirectXTK-GitHub-Test.yml, .azuredevops/pipelines/DirectXTK-GitHub.yml
Moved `ADOFeedGUID`, `ADOFeedURL`, `GDK_EDITION` and `VCPKG_TAG` to a shared variable group.
=> Update ADL YAML to use shared variables

Src/Keyboard.cpp, Src/Mouse.cpp
Change the way GameInput callbacks are handled for mouse/keyboard with multiple flags
=> Change the way GameInput callbacks are handled for mouse/keyboard
